### ISSUE TITLE
Feedback zum Testat vom 11.06.2015

### ISSUE THREAD

**Issue by RimacV** [tpe-lecture/group11-exercise4#10]
Die Lösung ist sehr gut.
- Alle Tests wurden bestanden. 
- Alle Klassen sind vollständig implementiert
- Live-Testat wurde gelöst
- Ich konnte keinen doppelten Code finden.

> 100 Punkte

**Comment by wagnst** [comment]
Vielen Dank für die super Punktzahl :-)
