### ISSUE TITLE
XOR-Verschlüsselung

### ISSUE THREAD

**Issue by maxGross** [tpe-lecture/group11-exercise4#3]

**Comment by wagnst** [comment]
ich mache es XOR ich mache es nicht 
:dancers: :P

**Comment by maxGross** [comment]
:D

**Comment by maxGross** [comment]
https://github.com/tpe-lecture/group11-exercise4/blame/master/src/de/wagnst/tpe/exercise/crypter/CrypterVerfahren.java#L29

minimum muss auf 1 max auf -1(per default)
